# Generated by Django 4.1.5 on 2023-02-08 07:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterplan',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 30, 4, 90971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BarterUserNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('child', 'Kid Account'), ('common', 'Common Account')], max_length=250)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_leader', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_branch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
