# Generated by Django 4.1.5 on 2023-02-08 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0002_alter_barterplan_expiration_barterusernode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterplan',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 20, 52, 19, 988890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BarterTradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_hash', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
