# Generated by Django 4.1.5 on 2023-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0004_remove_barterplan_expiration_barterplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteruser',
            name='is_co_founder',
            field=models.BooleanField(default=False),
        ),
    ]
