# Generated by Django 4.1.5 on 2023-02-18 16:32

import barter_auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0005_barteruser_is_co_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteruser',
            name='profile_image',
            field=models.URLField(default=barter_auth.utils.generate_default_image),
        ),
    ]
