# Generated by Django 4.1.5 on 2023-02-21 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0006_barteruser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteruser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VerificationActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('used', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'Verification'), (2, 'Recovery Password')], default=1)),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
