# Generated by Django 4.1.5 on 2023-02-21 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0007_barteruser_verified_verificationactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
