# Generated by Django 4.1.5 on 2023-02-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0007_bartertradingplan_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bartertradingplan',
            name='created_at',
        ),
    ]
