# Generated by Django 4.1.5 on 2023-02-23 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0008_remove_bartertradingplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartertradingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barterusernode',
            name='node_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barterusernode',
            name='reference_code',
            field=models.CharField(default='A', max_length=250),
            preserve_default=False,
        ),
    ]
