# Generated by Django 4.1.5 on 2023-02-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0008_alter_verificationactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationactions',
            name='token',
            field=models.BinaryField(),
        ),
    ]
