# Generated by Django 4.1.5 on 2023-02-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0009_bartertradingplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barterusernode',
            name='node_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10')], default=1),
        ),
    ]
