# Generated by Django 4.1.5 on 2023-02-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0009_alter_verificationactions_token'),
        ('barter_auth', '0010_alter_barterplan_user_and_more'),
    ]

    operations = [
    ]
