# Generated by Django 4.1.5 on 2023-02-27 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0010_alter_barterplan_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarterPlanCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='barter_auth.barterplan')),
            ],
        ),
    ]
