# Generated by Django 4.1.5 on 2023-02-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0011_merge_20230225_2245'),
        ('barter_auth', '0012_barterplancredentials_description'),
    ]

    operations = [
    ]
