# Generated by Django 4.1.5 on 2023-02-28 03:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0013_merge_20230228_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterplancredentials',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barterplancredentials',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 3, 25, 38, 552963, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
