# Generated by Django 4.1.5 on 2023-03-31 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0016_alter_barterplan_selected_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterusersecurityprofile',
            name='dni_back_image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Imagen DNI reverso'),
        ),
        migrations.AlterField(
            model_name='barterusersecurityprofile',
            name='dni_image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Imagen DNI frontal'),
        ),
        migrations.AlterField(
            model_name='barterusersecurityprofile',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Acepto terminos y condiciones'),
        ),
        migrations.AlterField(
            model_name='barterusersecurityprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
