# Generated by Django 4.1.5 on 2023-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0017_alter_barterusersecurityprofile_dni_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barteruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono'),
        ),
    ]
