# Generated by Django 4.1.5 on 2023-04-13 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0018_alter_barteruser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia')),
                ('calculation_process', models.TextField(blank=True, null=True, verbose_name='Procesos de calculo')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ganancia de plan',
                'verbose_name_plural': 'Ganancias de planes',
            },
        ),
        migrations.CreateModel(
            name='PlansEarningsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia')),
                ('calculation_process', models.TextField(blank=True, null=True, verbose_name='Procesos de calculo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='barter_auth.plansearnings', verbose_name='Ganancia de plan')),
            ],
            options={
                'verbose_name': 'Detalle de las ganancias por plan',
                'verbose_name_plural': 'Detalles de las ganancias por plan',
            },
        ),
    ]
