# Generated by Django 4.1.5 on 2023-04-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_alter_dailypercentagerevenue_percentage_amount'),
        ('barter_auth', '0019_plansearnings_plansearningsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansearningsdetail',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_earning_details', to='transactions.transaction', verbose_name='Transacción'),
        ),
    ]
