# Generated by Django 4.1.5 on 2023-05-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0006_leadershippooltype'),
        ('barter_auth', '0022_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteruser',
            name='leadership_pool_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='global_settings.leadershippooltype', verbose_name='Pool de liderazgo'),
        ),
    ]
