# Generated by Django 4.1.5 on 2023-05-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0025_alter_barteruser_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnilevelNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Nivel')),
                ('in_network_through', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unilevel_network_users_through', to=settings.AUTH_USER_MODEL, verbose_name='A traves de')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unilevel_network', to=settings.AUTH_USER_MODEL, verbose_name='Red de')),
                ('user_in_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unilevel_network_in', to=settings.AUTH_USER_MODEL, verbose_name='Usuario en red')),
            ],
            options={
                'verbose_name': 'Red de usuario',
                'verbose_name_plural': 'Redes de usuarios',
            },
        ),
    ]
