# Generated by Django 4.1.5 on 2023-05-19 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0008_userversioning'),
        ('barter_auth', '0026_unilevelnetwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barteruser',
            name='referrals',
        ),
        migrations.AddField(
            model_name='barteruser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='barteruser',
            name='leadership_pool_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='global_settings.leadershippooltype', verbose_name='Pool de liderazgo'),
        ),
    ]
