# Generated by Django 4.1.5 on 2023-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0027_remove_barteruser_referrals_barteruser_referred_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barteruser',
            name='versioning',
        ),
        migrations.RemoveField(
            model_name='plansearnings',
            name='calculation_process',
        ),
        migrations.AddField(
            model_name='plansearnings',
            name='earning_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganancia pagada'),
        ),
        migrations.AddField(
            model_name='plansearnings',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='plansearnings',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='plansearnings',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganancia'),
        ),
    ]
