# Generated by Django 4.1.5 on 2023-05-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0028_remove_plansearnings_calculation_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansearningsdetail',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel'),
        ),
    ]
