# Generated by Django 4.1.5 on 2023-05-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0029_plansearningsdetail_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteruser',
            name='can_fill_kyc',
            field=models.BooleanField(default=True, verbose_name='Puede rellenar KYC'),
        ),
    ]
