# Generated by Django 4.1.5 on 2023-06-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0031_barteruser_can_fill_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
