# Generated by Django 4.1.5 on 2023-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0032_alter_userwallet_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='transaction_hash',
            field=models.CharField(blank=True, default='-', max_length=250),
        ),
    ]
