# Generated by Django 4.1.5 on 2023-07-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0054_tradingearnings_reinvestment_and_more'),
        ('global_settings', '0017_tradingplans_kitplanunilevelpercentage_kit_plan_and_more'),
        ('barter_auth', '0033_alter_referral_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterplan',
            name='cap_reached',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tope alcanzado'),
        ),
        migrations.AddField(
            model_name='barterplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_plans', to='global_settings.kitplan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='barterplan',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_plans', to='transactions.transaction', verbose_name='Transacción'),
        ),
        migrations.AddField(
            model_name='bartertradingplan',
            name='cap_reached',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tope alcanzado'),
        ),
        migrations.AddField(
            model_name='bartertradingplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_plans', to='global_settings.tradingplans', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='bartertradingplan',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_plans', to='transactions.transaction', verbose_name='Transacción'),
        ),
    ]
