# Generated by Django 4.1.5 on 2023-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_exchanges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN REVIEW'), (2, 'VERIFIED'), (3, 'REJECTED')], default=1),
            preserve_default=False,
        ),
    ]
