# Generated by Django 4.1.5 on 2023-02-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='exchanges',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.IntegerField(choices=[(0, 'IN REVIEW'), (1, 'VERIFIED'), (2, 'REJECTED')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
