# Generated by Django 4.1.5 on 2023-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transaction_exchanges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='co_founder_invest',
            field=models.BooleanField(default=False),
        ),
    ]
