# Generated by Django 4.1.5 on 2023-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_co_founder_invest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPercentageRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percentage_amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
