# Generated by Django 4.1.5 on 2023-02-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_dailypercentagerevenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPercentageRevenue',
        ),
    ]
