# Generated by Django 4.1.5 on 2023-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_delete_dailypercentagerevenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPercentageRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percentage_amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher_screenshot',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_provider',
            field=models.CharField(choices=[('binance', 'BINANCE'), ('kucoin', 'KUCOIN'), ('other', 'OTHER')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
