# Generated by Django 4.1.5 on 2023-02-27 09:35

from django.db import migrations
from re import search


def add_transaction_empty_fields(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')

    for t in Transaction.objects.all():
        if search('Kit Plan', t.description):
            t.transaction_type = 'kit-plan'

        if search('Trading', t.description):
            t.transaction_type = 'trading'

        t.transaction_type = 'invest'

        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transaction_user'),
    ]

    operations = [
        migrations.RunPython(add_transaction_empty_fields, reverse_code=migrations.RunPython.noop)
    ]
