# Generated by Django 4.1.5 on 2023-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_prepopulate_transactions__transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('kit-plan', 'Kit Plan'), ('trading', 'Trading'), ('co-founder', 'Co-founder'), ('neutral', 'Neutral')], default='invest', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_provider',
            field=models.CharField(choices=[('binance', 'BINANCE'), ('kucoin', 'KUCOIN'), ('coinbase', 'COINBASE'), ('bybit', 'BYBIT'), ('other', 'OTHER')], max_length=255),
        ),
    ]
