# Generated by Django 4.1.5 on 2023-02-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_network',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
