# Generated by Django 4.1.5 on 2023-02-28 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0012_transaction_transaction_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255)),
                ('wallet_provider', models.CharField(choices=[('binance', 'BINANCE'), ('kucoin', 'KUCOIN'), ('coinbase', 'COINBASE'), ('bybit', 'BYBIT'), ('other', 'OTHER')], max_length=255)),
                ('wallet_network', models.CharField(default='-', max_length=255)),
                ('transaction_hash', models.CharField(max_length=250)),
                ('voucher_screenshot', models.CharField(max_length=255)),
                ('confirmation_screenshot', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_status', models.IntegerField(choices=[(0, 'IN REVIEW'), (1, 'VERIFIED'), (2, 'REJECTED')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
