# Generated by Django 4.1.5 on 2023-03-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_withdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypercentagerevenue',
            options={'verbose_name': 'Porcentaje de ganancia diario', 'verbose_name_plural': 'Porcentajes de ganancia diarios'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': 'Retiro', 'verbose_name_plural': 'Retiros'},
        ),
    ]
