# Generated by Django 4.1.5 on 2023-03-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_dailypercentagerevenue_options_and_more'),
        ('transactions', '0016_transaction_transaction_date'),
    ]

    operations = [
    ]
