# Generated by Django 4.1.5 on 2023-03-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_merge_20230312_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_screenshot', models.CharField(max_length=255, verbose_name='Captura de voucher')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='Fecha de transaccion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenshots', to='transactions.transaction', verbose_name='Transaccion')),
            ],
            options={
                'verbose_name': 'Captura de transaccion',
                'verbose_name_plural': 'Capturas de transacciones',
            },
        ),
    ]
