# Generated by Django 4.1.5 on 2023-03-31 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0018_transactionscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='co_founder_invest',
            field=models.BooleanField(default=False, verbose_name='Inversión de cofundador'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de transacción'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(max_length=250, verbose_name='Hash de transacción'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_network',
            field=models.CharField(default='-', max_length=250, verbose_name='Red/Moneda'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.IntegerField(choices=[(0, 'IN REVIEW'), (1, 'VERIFIED'), (2, 'REJECTED')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('kit-plan', 'Kit Plan'), ('trading', 'Trading'), ('co-founder', 'Co-founder'), ('neutral', 'Neutral')], max_length=250, verbose_name='Tipo de transacción'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_screenshot',
            field=models.CharField(max_length=255, verbose_name='Captura de voucher'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(max_length=255, verbose_name='Dirección de billetera'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_provider',
            field=models.CharField(choices=[('binance', 'BINANCE'), ('kucoin', 'KUCOIN'), ('coinbase', 'COINBASE'), ('bybit', 'BYBIT'), ('other', 'OTHER')], max_length=255, verbose_name='Proveedor de billetera'),
        ),
        migrations.CreateModel(
            name='UserRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Inversion en el momento')),
                ('earnings_percentage', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Porcentaje de Ganancias')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancias')),
                ('earnings_date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('percentage_revenue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_revenues', to='transactions.dailypercentagerevenue', verbose_name='Ganancias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ganancia de usuario',
                'verbose_name_plural': 'Ganancias de usuarios',
            },
        ),
    ]
