# Generated by Django 4.1.5 on 2023-03-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypercentagerevenue',
            name='percentage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userrevenue',
            name='earnings_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje de Ganancias'),
        ),
    ]
