# Generated by Django 4.1.5 on 2023-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_transaction_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='source_of_profit',
            field=models.CharField(choices=[(0, 'TRADING'), (1, 'KIT_PLAN')], default='TRADING', max_length=255),
        ),
    ]
