# Generated by Django 4.1.5 on 2023-04-03 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_transaction_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypercentagerevenue',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailypercentagerevenue',
            name='percentage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.88)]),
        ),
    ]
