# Generated by Django 4.1.5 on 2023-04-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0022_withdrawal_source_of_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTradingEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ROI, omita el registro puesto que el sistema lo calcula.')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, verbose_name='Mes')),
                ('year', models.IntegerField(default=2023, verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Ganancia mensual de trading',
                'verbose_name_plural': 'Ganancias mensuales de trading',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTradingEarningsPerLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancias')),
                ('calculation_process', models.TextField(blank=True, null=True, verbose_name='Procesos de calculo')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('monthly_trading_earnings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='transactions.monthlytradingearnings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_trading_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
