# Generated by Django 4.1.5 on 2023-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_monthlytradingearnings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytradingearningsperleader',
            options={'verbose_name': 'Ganancia mensual de trading por líder', 'verbose_name_plural': 'Ganancias mensuales de trading por líder'},
        ),
        migrations.AlterField(
            model_name='monthlytradingearnings',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ROI, omita el registro puesto que el sistema lo calcula.'),
        ),
    ]
