# Generated by Django 4.1.5 on 2023-04-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_monthlytradingearningsperleader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='amount_before_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='confirmation_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawals/confirmations/'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='voucher_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawals/vouchers/'),
        ),
    ]
