# Generated by Django 4.1.5 on 2023-04-08 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0025_withdrawal_amount_before_fee_withdrawal_fee_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='amount_before_fee',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='amount_after_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto después de la comisión'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='confirmation_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawals/confirmations/', verbose_name='Captura de confirmación'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la comisión'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='source_of_profit',
            field=models.CharField(choices=[('TRADING', 'TRADING'), ('KIT_PLAN', 'KIT_PLAN')], default='TRADING', max_length=255, verbose_name='Tipo de retiro'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de transacción'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hash de transacción'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction_status',
            field=models.IntegerField(choices=[(0, 'IN REVIEW'), (1, 'VERIFIED'), (2, 'REJECTED')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='voucher_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawals/vouchers/', verbose_name='Captura de voucher'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(max_length=255, verbose_name='Dirección de billetera'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_network',
            field=models.CharField(default='-', max_length=255, verbose_name='Red de billetera'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_provider',
            field=models.CharField(choices=[('binance', 'BINANCE'), ('kucoin', 'KUCOIN'), ('coinbase', 'COINBASE'), ('bybit', 'BYBIT'), ('other', 'OTHER')], max_length=255, verbose_name='Proveedor de billetera'),
        ),
    ]
