# Generated by Django 4.1.5 on 2023-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_remove_withdrawal_amount_before_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='other_wallet_provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro proveedor de billetera'),
        ),
    ]
