# Generated by Django 4.1.5 on 2023-04-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_dailypercentagerevenue_date_and_more'),
        ('transactions', '0027_withdrawal_other_wallet_provider'),
    ]

    operations = [
    ]
