# Generated by Django 4.1.5 on 2023-04-15 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0029_alter_dailypercentagerevenue_percentage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount_after_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total pagado'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% Comisión por Retiro'),
        ),
        migrations.CreateModel(
            name='CumulativeRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancias totales')),
                ('total_to_withdraw', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a retirar')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, verbose_name='Mes')),
                ('year', models.IntegerField(default=2023, verbose_name='Año')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cumulative_revenues', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ganancia acumulada de usuario',
                'verbose_name_plural': 'Ganancias acumuladas de usuarios',
            },
        ),
        migrations.AddField(
            model_name='userrevenue',
            name='cumulative_revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='transactions.cumulativerevenue', verbose_name='Ganancia acumulada'),
        ),
    ]
