# Generated by Django 4.1.5 on 2023-04-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0030_alter_withdrawal_amount_after_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypercentagerevenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailypercentagerevenue',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='dailypercentagerevenue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado en'),
        ),
        migrations.CreateModel(
            name='UserDailyTradingRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Inversion en el momento')),
                ('earnings_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje de Ganancias')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancias')),
                ('earnings_date', models.DateField(verbose_name='Fecha')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('percentage_revenue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_daily_trading_revenues', to='transactions.dailypercentagerevenue', verbose_name='Porcentaje de ganancia')),
                ('trading_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_earnings', to='transactions.transaction', verbose_name='Transaccion de trading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_trading_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ganancia diaria de trading de usuario',
                'verbose_name_plural': 'Ganancias diarias de trading de usuarios',
            },
        ),
    ]
