# Generated by Django 4.1.5 on 2023-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_cofounderearningbyproducts_cofounderearningbytrading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofounderearningbyproducts',
            name='trimester',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trimestre, campo calculado automáticamente'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbytrading',
            name='trimester',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trimestre, campo calculado automáticamente'),
        ),
    ]
