# Generated by Django 4.1.5 on 2023-04-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0033_rename_percentage_revenue_userdailytradingrevenue_daily_percentage_revenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypercentagerevenue',
            options={'verbose_name': 'Porcentaje de ganancia diario de trading', 'verbose_name_plural': 'Porcentajes de ganancia diarios de trading'},
        ),
    ]
