# Generated by Django 4.1.5 on 2023-04-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0034_alter_dailypercentagerevenue_options'),
        ('transactions', '0034_detailcofounderearningbyproducts_process'),
    ]

    operations = [
    ]
