# Generated by Django 4.1.5 on 2023-04-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_merge_20230429_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='source_of_profit',
            field=models.CharField(choices=[('TRADING', 'TRADING'), ('KIT_PLAN', 'KIT_PLAN'), ('CO_FOUNDER', 'CO_FOUNDER')], default='TRADING', max_length=255, verbose_name='Tipo de retiro'),
        ),
    ]
