# Generated by Django 4.1.5 on 2023-05-02 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global_settings', '0006_leadershippooltype'),
        ('transactions', '0036_alter_withdrawal_source_of_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofounderearningbyproducts',
            name='leadership_pool_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cofounder_earnings_by_products', to='global_settings.leadershippooltype', verbose_name='Pool de liderazgo'),
        ),
        migrations.AddField(
            model_name='cofounderearningbytrading',
            name='leadership_pool_type',
            field=models.ForeignKey(null=tuple, on_delete=django.db.models.deletion.PROTECT, related_name='cofounder_earnings_by_trading', to='global_settings.leadershippooltype', verbose_name='Pool de liderazgo'),
            preserve_default=tuple,
        ),
        migrations.AlterField(
            model_name='cofounderearningbyproducts',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbyproducts',
            name='trimester',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trimestre (Auto)'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbytrading',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbytrading',
            name='trimester',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trimestre (Auto)'),
        ),
        migrations.AlterField(
            model_name='cumulativerevenue',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='detailcofounderearningbyproducts',
            name='co_founder_earning_by_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='transactions.cofounderearningbyproducts', verbose_name='Ganancia de cofundador por producto'),
        ),
        migrations.AlterField(
            model_name='detailcofounderearningbyproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='co_founder_earning_by_products', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='detailcofounderearningbytrading',
            name='co_founder_earning_by_trading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='transactions.cofounderearningbytrading', verbose_name='Ganancia de cofundador de trading'),
        ),
        migrations.AlterField(
            model_name='detailcofounderearningbytrading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='co_founder_earning_by_trading', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='monthlytradingearnings',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5, verbose_name='Mes'),
        ),
    ]
