# Generated by Django 4.1.5 on 2023-05-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_cofounderearningbyproducts_leadership_pool_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrevenue',
            name='cumulative_revenue',
        ),
        migrations.AddField(
            model_name='userdailytradingrevenue',
            name='cumulative_revenue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='transactions.cumulativerevenue', verbose_name='Ganancia acumulada'),
        ),
    ]
