# Generated by Django 4.1.5 on 2023-05-03 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0037_cofounderearningbyproducts_leadership_pool_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReInvestments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('type_re_investment', models.IntegerField(choices=[(0, 'Trading'), (1, 'Co-Founder')], verbose_name='Tipo de reinversión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='re_investments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reinversión',
                'verbose_name_plural': 'Reinversiones',
            },
        ),
    ]
