# Generated by Django 4.1.5 on 2023-05-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_remove_userrevenue_cumulative_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrevenue',
            name='user',
        ),
    ]
