# Generated by Django 4.1.5 on 2023-05-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_reinvestments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinvestments',
            name='type_re_investment',
            field=models.CharField(choices=[('Trading', 'Trading'), ('Co-Founder', 'Co-Founder')], max_length=20, verbose_name='Tipo de reinversión'),
        ),
    ]
