# Generated by Django 4.1.5 on 2023-05-03 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0039_remove_userrevenue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailytradingrevenue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
