# Generated by Django 4.1.5 on 2023-05-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_alter_userdailytradingrevenue_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRevenue',
        ),
    ]
