# Generated by Django 4.1.5 on 2023-05-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_monthlytradingearningsperleader_earnings_paid'),
        ('transactions', '0041_delete_userrevenue'),
    ]

    operations = [
    ]
