# Generated by Django 4.1.5 on 2023-05-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_merge_20230503_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailytradingrevenue',
            name='reinvestment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_trading_earnings', to='transactions.reinvestments', verbose_name='Reinversion'),
        ),
        migrations.AlterField(
            model_name='userdailytradingrevenue',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_earnings', to='transactions.transaction', verbose_name='Transaccion de trading'),
        ),
    ]
