# Generated by Django 4.1.5 on 2023-05-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_merge_20230503_0037'),
        ('transactions', '0043_userdailytradingrevenue_reinvestment_and_more'),
    ]

    operations = [
    ]
