# Generated by Django 4.1.5 on 2023-05-03 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_merge_20230503_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofounderearningbyproducts',
            name='earning_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Porcentaje de ganancias'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbytrading',
            name='earning_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Porcentaje de ganancias'),
        ),
    ]
