# Generated by Django 4.1.5 on 2023-05-22 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0045_alter_cofounderearningbyproducts_earning_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cofounder_balance', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Balance de cofundador')),
                ('cofounder_earnings', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Ganancias de cofundador')),
                ('trading_balance', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Balance de trading')),
                ('trading_earnings', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Ganancias de trading personales')),
                ('trading_network_earnings', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Ganancias de trading de red')),
                ('kitplan_balance', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Balance de kitplan')),
                ('kitplan_network_earnings', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Ganancias de kitplan de red')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
        migrations.CreateModel(
            name='BalanceTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('unique_code', models.CharField(max_length=5, unique=True, verbose_name='Código único para developers')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion corta')),
                ('app_lookup', models.CharField(max_length=50, verbose_name='App del modelo')),
                ('model_lookup', models.CharField(max_length=100, verbose_name='Nombre del modelo')),
                ('balance_lookup_field', models.CharField(max_length=50, verbose_name='Columna de balance que modifica')),
                ('is_income', models.BooleanField(verbose_name='Es ingreso')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Tipo de trasanccion en balance',
                'verbose_name_plural': 'Tipos de transaccion en balance',
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField(verbose_name='Id de objeto')),
                ('object_date', models.DateTimeField(verbose_name='Fecha de transaccion de objeto')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Monto de transaccion')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='transactions.balance', verbose_name='Balance')),
                ('balance_transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_history', to='transactions.balancetransactiontype', verbose_name='Tipo de transaccion en balance')),
            ],
            options={
                'verbose_name': 'Historial de balance',
                'verbose_name_plural': 'Historial de balances',
            },
        ),
    ]
