# Generated by Django 4.1.5 on 2023-05-26 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0047_kitplannetworkearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypercentagerevenue',
            name='percentage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.88)]),
        ),
    ]
