# Generated by Django 4.1.5 on 2023-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0049_transaction_calculated_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='calculated_earnings',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ganancias calculadas'),
        ),
    ]
