# Generated by Django 4.1.5 on 2023-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0050_alter_transaction_calculated_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailytradingrevenue',
            name='calculated_earnings',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ganancias de red calculadas'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbyproducts',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbytrading',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cumulativerevenue',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='monthlytradingearnings',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='monthlytradingearningsperleader',
            name='earnings_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganancias pagadas'),
        ),
    ]