# Generated by Django 4.1.5 on 2023-06-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0051_userdailytradingrevenue_calculated_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='general_balance',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Balance que el usuario puede utilizar para cualquier producto del dashboard', max_digits=21, verbose_name='Balance general'),
        ),
    ]