# Generated by Django 4.1.5 on 2023-06-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter_auth', '0033_alter_referral_transaction_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global_settings', '0016_alter_businesswallet_hash'),
        ('transactions', '0052_balance_general_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_percentage_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje de ganancia usado')),
                ('current_investment', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Inversion actual')),
                ('earnings', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Ganancias')),
                ('calculation_process', models.TextField(blank=True, null=True, verbose_name='Proceso de calculo')),
                ('calculated_earnings', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ganancias calculadas')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('trading_percentage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_earnings', to='transactions.monthlytradingearnings', verbose_name='Porcentaje de ganancias')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_earnings', to='transactions.transaction', verbose_name='Transacción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ganancias de Trading',
                'verbose_name_plural': 'Ganancias de Trading',
            },
        ),
        migrations.CreateModel(
            name='TradingNetWorkEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Nivel')),
                ('level_earnings_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje de ganancias de nivel')),
                ('current_investment', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Inversion actual')),
                ('earnings', models.DecimalField(decimal_places=4, max_digits=21, verbose_name='Ganancias')),
                ('calculation_process', models.TextField(blank=True, null=True, verbose_name='Proceso de calculo')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('trading_earnings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_network_earnings', to='transactions.tradingearnings', verbose_name='Ganancias de Trading')),
                ('trading_percentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_netow_earnings', to='transactions.monthlytradingearnings', verbose_name='Porcentaje de ganancias')),
                ('trading_unilevel_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_network_earnings', to='global_settings.tradingunilevelpercentage', verbose_name='Porcentaje de red de referidos de Trading')),
                ('unilevel_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_network_earnings', to='barter_auth.unilevelnetwork', verbose_name='Red de referidos de Trading')),
            ],
            options={
                'verbose_name': 'Red de referidos de Trading(Ganancias)',
                'verbose_name_plural': 'Red de referidos de Trading(Ganancias)',
            },
        ),
    ]
