# Generated by Django 4.1.5 on 2023-07-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0053_tradingearnings_tradingnetworkearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingearnings',
            name='reinvestment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_earnings', to='transactions.reinvestments', verbose_name='Re-inversion'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbyproducts',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cofounderearningbytrading',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='cumulativerevenue',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='monthlytradingearnings',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='tradingearnings',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_earnings', to='transactions.transaction', verbose_name='Transacción'),
        ),
    ]
