# Generated by Django 4.1.5 on 2023-04-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_verifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KYCReviewResults',
            new_name='KYCReviewResult',
        ),
    ]
