# Generated by Django 4.1.5 on 2023-04-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFunnelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre en enlace de embudo')),
                ('display_name', models.CharField(max_length=120, verbose_name='Nombre a mostrar')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp_phone_number', models.CharField(max_length=15, verbose_name='Numero de Whatsapp')),
                ('facebook_account_url', models.URLField(verbose_name='Enlace de Facebook')),
                ('twitter_account_url', models.URLField(verbose_name='Enlace de Twitter')),
                ('custom_video_url', models.URLField(verbose_name='Video de Youtube')),
                ('profile_image', models.ImageField(upload_to='', verbose_name='Imagen de perfil')),
                ('enabled', models.BooleanField(verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_funnel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptor_email', models.EmailField(max_length=254, verbose_name='Email de suscriptor')),
                ('sent_emails', models.PositiveSmallIntegerField(verbose_name='Cant. de emails enviados')),
                ('enabled', models.BooleanField(verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='sales_funnel.salesfunnelowner', verbose_name='Suscrito a')),
            ],
        ),
    ]
