# Generated by Django 4.1.5 on 2023-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='subscriptor_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email de suscriptor'),
        ),
    ]
