# Generated by Django 4.1.5 on 2023-04-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0003_alter_salesfunnelowner_custom_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'verbose_name': 'Suscripcion de embudo', 'verbose_name_plural': 'Suscripciones de embudos'},
        ),
        migrations.AlterModelOptions(
            name='salesfunnelowner',
            options={'verbose_name': 'Embudo de venta de clientes', 'verbose_name_plural': 'Embudos de venta de clientes'},
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='sent_emails',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cant. de emails enviados'),
        ),
    ]
