# Generated by Django 4.1.5 on 2023-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0004_alter_newslettersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='salesfunnelowner',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
