# Generated by Django 4.1.5 on 2023-04-22 18:05

import django.core.validators
from django.db import migrations, models
import sales_funnel.custom_storage
import sales_funnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0006_funnelstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelstep',
            name='thumbnail_image',
            field=models.ImageField(blank=True, storage=sales_funnel.custom_storage.FunnelStepThumbnailImageStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagen de previsualizacion'),
        ),
        migrations.AlterField(
            model_name='salesfunnelowner',
            name='profile_image',
            field=models.ImageField(blank=True, storage=sales_funnel.custom_storage.MediaStorage(), upload_to=sales_funnel.models.get_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagen de perfil'),
        ),
    ]
