# Generated by Django 4.1.5 on 2023-04-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawaltype',
            options={'verbose_name': 'Tipo de retiros', 'verbose_name_plural': 'Tipos de retiros'},
        ),
    ]
