# Generated by Django 4.1.5 on 2023-04-13 22:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_alter_withdrawaltype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('short_descripcion', models.CharField(max_length=100, verbose_name='Descripcion corta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('business_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volumen de negocio')),
                ('earnings_cap', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Techo de ganancias')),
                ('allow_repurchase', models.BooleanField(verbose_name='Permitir recompra')),
                ('can_be_upgraded', models.BooleanField(verbose_name='Permitir subir de plan')),
                ('enabled', models.BooleanField(verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Kit Plan',
                'verbose_name_plural': 'Kit Plans',
            },
        ),
        migrations.CreateModel(
            name='KitPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Posicion')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('kit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='global_settings.kitplan', verbose_name='Kit Plan')),
            ],
        ),
    ]
