# Generated by Django 4.1.5 on 2023-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0003_kitplan_kitplandetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitplandetail',
            options={'verbose_name': 'Detalle de Kit Plan', 'verbose_name_plural': 'Detalles de Kit Plan'},
        ),
        migrations.RemoveField(
            model_name='kitplan',
            name='short_descripcion',
        ),
        migrations.AddField(
            model_name='kitplan',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descripcion corta'),
        ),
    ]
