# Generated by Django 4.1.5 on 2023-04-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0004_alter_kitplandetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Blockchain')),
            ],
            options={
                'verbose_name': 'Blockchain',
                'verbose_name_plural': 'Blockchains',
            },
        ),
        migrations.CreateModel(
            name='ExchangeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Red/Moneda')),
            ],
            options={
                'verbose_name': 'Red / Moneda',
                'verbose_name_plural': 'Redes / Monedas',
            },
        ),
        migrations.CreateModel(
            name='BusinessWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True, verbose_name='Hash de la billetera')),
                ('enabled', models.BooleanField(verbose_name='Habilitado')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_wallets', to='global_settings.blockchainchoices', verbose_name='Blockchain')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_wallets', to='global_settings.exchangechoices', verbose_name='Red/Moneda')),
            ],
            options={
                'verbose_name': 'Billetera de empresa',
                'verbose_name_plural': 'Billeteras de empresa',
            },
        ),
    ]
