# Generated by Django 4.1.5 on 2023-05-02 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0005_blockchainchoices_exchangechoices_businesswallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipPoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('earning_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Porcentaje de ganancia')),
                ('enabled', models.BooleanField(verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Pool de liderazgo',
                'verbose_name_plural': 'Pools de liderazgo',
            },
        ),
    ]
