# Generated by Django 4.1.5 on 2023-05-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0009_kitplanunilevelpercentage_tradingunilevelpercentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVersioning',
        ),
    ]
