# Generated by Django 4.1.5 on 2023-05-29 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global_settings', '0011_businesswallettype_businesswallet_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootBarterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_barter_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario raíz')),
            ],
            options={
                'verbose_name': 'Usuario raíz de las redes',
                'verbose_name_plural': 'Usuarios raices de las redes',
            },
        ),
    ]
