# Generated by Django 4.1.5 on 2023-06-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0012_rootbarteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Criptomoneda',
                'verbose_name_plural': 'Criptomonedas',
            },
        ),
        migrations.AlterModelOptions(
            name='exchangechoices',
            options={'verbose_name': 'Exchange', 'verbose_name_plural': 'Exchanges'},
        ),
        migrations.AlterField(
            model_name='blockchainchoices',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='businesswallet',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_wallets', to='global_settings.exchangechoices', verbose_name='Exchange'),
        ),
        migrations.AlterField(
            model_name='exchangechoices',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='businesswallet',
            name='cryptocurrency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_wallets', to='global_settings.cryptocurrencychoices', verbose_name='Criptomoneda'),
        ),
    ]
