# Generated by Django 4.1.5 on 2023-06-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0013_cryptocurrencychoices_alter_exchangechoices_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitPlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('enabled', models.BooleanField(verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
            ],
            options={
                'verbose_name': 'Categorias de Kit Plan',
                'verbose_name_plural': 'Categorias de Kit Plan',
            },
        ),
        migrations.AddField(
            model_name='kitplan',
            name='kit_plan_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_plans', to='global_settings.kitplancategory', verbose_name='Categoria'),
        ),
    ]
