# Generated by Django 4.1.5 on 2023-06-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0014_kitplancategory_kitplan_kit_plan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswallet',
            name='hash',
            field=models.CharField(max_length=40, verbose_name='Hash de la billetera'),
        ),
        migrations.AlterField(
            model_name='businesswallet',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='global_settings.businesswallettype', verbose_name='Tipo de billetera'),
        ),
    ]
