# Generated by Django 4.1.5 on 2023-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0015_alter_businesswallet_hash_alter_businesswallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswallet',
            name='hash',
            field=models.CharField(max_length=255, verbose_name='Hash de la billetera'),
        ),
    ]